import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { cp, rm } from "node:fs/promises";
import type { DSTConfig } from "../config.js";
import { parseModOverrides } from "./mods.js";
import { installedModDir, modOverridesPath, modsDir, modsSetupPath } from "./paths.js";
import { workshopItemDir } from "./steamcmd.js";

/**
 * จัดการ dedicated_server_mods_setup.lua + ติดตั้ง workshop mods ลง <install>/mods
 *
 * แกน (เบา ทำเสมอ): sync dedicated_server_mods_setup.lua จาก modoverrides.lua
 *   → engine จะโหลด+ใช้ม็อดผ่าน UGC ให้เองตอน start
 * เสริม (ปุ่ม): โหลด workshop ผ่าน SteamCMD แล้ว copy เป็น mods/workshop-<id>
 *   (portable, ไม่ต้อง boot เกมเพื่อโหลด — แทนวิธี warm-up เดิม)
 */

/** marker บรรทัดแรก — ใช้ดูว่าไฟล์นี้ "ระบบสร้าง" (จะ regenerate ได้) หรือคนเขียนเอง (ห้ามทับ) */
const MARKER = "-- generated by DST Manager (from modoverrides.lua) — do not edit by hand";

/** อ่าน workshop id ที่ enabled จาก modoverrides.lua (ลอง shard ตามลำดับที่ส่งมา) */
export function collectEnabledWorkshopIds(dst: DSTConfig, shards: string[] = ["Master"]): string[] {
  for (const shard of shards) {
    const path = modOverridesPath(dst, shard);
    if (!existsSync(path)) continue;
    try {
      const mods = parseModOverrides(readFileSync(path, "utf8"));
      return [...new Set(mods.filter((m) => m.enabled).map((m) => m.id))];
    } catch {
      // ไฟล์พัง → ลอง shard ถัดไป
    }
  }
  return [];
}

/**
 * เขียน dedicated_server_mods_setup.lua จาก ids (regenerate ทั้งไฟล์)
 * เคารพไฟล์ที่คนเขียนเอง: ถ้ามีไฟล์เดิมที่ "ไม่ขึ้นต้นด้วย MARKER" จะไม่ทับ
 * คืน { wrote, manual } — manual=true แปลว่าเจอไฟล์ที่คนทำเอง เลยข้าม
 */
export function writeModsSetup(dst: DSTConfig, ids: string[]): { wrote: boolean; manual: boolean } {
  const path = modsSetupPath(dst);
  if (existsSync(path)) {
    try {
      if (!readFileSync(path, "utf8").startsWith(MARKER)) return { wrote: false, manual: true };
    } catch {
      // อ่านไม่ได้ → ถือว่าเขียนทับได้
    }
  }
  mkdirSync(modsDir(dst), { recursive: true });
  const body = [MARKER, ...ids.map((id) => `ServerModSetup("${id}")`), ""].join("\n");
  writeFileSync(path, body, "utf8");
  return { wrote: true, manual: false };
}

/** sync: อ่าน modoverrides → เขียน setup.lua (เคารพไฟล์ที่คนทำเอง); คืน ids + ผลการเขียน */
export function syncModsSetup(
  dst: DSTConfig,
  shards: string[] = ["Master"],
): { ids: string[]; wrote: boolean; manual: boolean } {
  const ids = collectEnabledWorkshopIds(dst, shards);
  const r = writeModsSetup(dst, ids);
  return { ids, ...r };
}

/** id ที่ SteamCMD โหลดมาเสร็จแล้ว (มีโฟลเดอร์ workshop content จริง) */
export function downloadedWorkshopIds(ids: string[]): string[] {
  return ids.filter((id) => existsSync(workshopItemDir(id)));
}

/**
 * copy workshop content ที่โหลดมา → <install>/mods/workshop-<id> (refresh ทับของเดิม)
 * คืน { copied, missing } — missing = id ที่ยังไม่มีโฟลเดอร์ที่โหลดมา (โหลดไม่สำเร็จ)
 */
export async function copyDownloadedMods(
  dst: DSTConfig,
  ids: string[],
): Promise<{ copied: string[]; missing: string[] }> {
  const copied: string[] = [];
  const missing: string[] = [];
  for (const id of ids) {
    const src = workshopItemDir(id);
    if (!existsSync(src)) {
      missing.push(id);
      continue;
    }
    const dest = installedModDir(dst, id);
    await rm(dest, { recursive: true, force: true });
    await cp(src, dest, { recursive: true });
    copied.push(id);
  }
  return { copied, missing };
}
