import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { cp, rm } from "node:fs/promises";
import { basename, join } from "node:path";
import type { DSTConfig } from "../config.js";
import { extractArchive } from "./archive.js";
import { fetchWorkshopFileUrls, parseModOverrides } from "./mods.js";
import { installedModDir, modOverridesPath, modsDir, modsSetupPath } from "./paths.js";
import { workshopItemDir } from "./steamcmd.js";

/**
 * จัดการ dedicated_server_mods_setup.lua + ติดตั้ง workshop mods ลง <install>/mods
 *
 * แกน (เบา ทำเสมอ): sync dedicated_server_mods_setup.lua จาก modoverrides.lua
 *   → engine จะโหลด+ใช้ม็อดผ่าน UGC ให้เองตอน start
 * เสริม (ปุ่ม): โหลด workshop ผ่าน SteamCMD แล้ว copy เป็น mods/workshop-<id>
 *   (portable, ไม่ต้อง boot เกมเพื่อโหลด — แทนวิธี warm-up เดิม)
 */

/** marker บรรทัดแรก — ใช้ดูว่าไฟล์นี้ "ระบบสร้าง" (จะ regenerate ได้) หรือคนเขียนเอง (ห้ามทับ) */
const MARKER = "-- generated by DST Manager (from modoverrides.lua) — do not edit by hand";

/** อ่าน workshop id ที่ enabled จาก modoverrides.lua (ลอง shard ตามลำดับที่ส่งมา) */
export function collectEnabledWorkshopIds(dst: DSTConfig, shards: string[] = ["Master"]): string[] {
  for (const shard of shards) {
    const path = modOverridesPath(dst, shard);
    if (!existsSync(path)) continue;
    try {
      const mods = parseModOverrides(readFileSync(path, "utf8"));
      return [...new Set(mods.filter((m) => m.enabled).map((m) => m.id))];
    } catch {
      // ไฟล์พัง → ลอง shard ถัดไป
    }
  }
  return [];
}

/**
 * เขียน dedicated_server_mods_setup.lua จาก ids (regenerate ทั้งไฟล์)
 * เคารพไฟล์ที่คนเขียนเอง: ถ้ามีไฟล์เดิมที่ "ไม่ขึ้นต้นด้วย MARKER" จะไม่ทับ
 * คืน { wrote, manual } — manual=true แปลว่าเจอไฟล์ที่คนทำเอง เลยข้าม
 */
export function writeModsSetup(dst: DSTConfig, ids: string[]): { wrote: boolean; manual: boolean } {
  const path = modsSetupPath(dst);
  if (existsSync(path)) {
    try {
      if (!readFileSync(path, "utf8").startsWith(MARKER)) return { wrote: false, manual: true };
    } catch {
      // อ่านไม่ได้ → ถือว่าเขียนทับได้
    }
  }
  mkdirSync(modsDir(dst), { recursive: true });
  const body = [MARKER, ...ids.map((id) => `ServerModSetup("${id}")`), ""].join("\n");
  writeFileSync(path, body, "utf8");
  return { wrote: true, manual: false };
}

/** sync: อ่าน modoverrides → เขียน setup.lua (เคารพไฟล์ที่คนทำเอง); คืน ids + ผลการเขียน */
export function syncModsSetup(
  dst: DSTConfig,
  shards: string[] = ["Master"],
): { ids: string[]; wrote: boolean; manual: boolean } {
  const ids = collectEnabledWorkshopIds(dst, shards);
  const r = writeModsSetup(dst, ids);
  return { ids, ...r };
}

/** id ที่ SteamCMD โหลดมาเสร็จแล้ว (มีโฟลเดอร์ workshop content จริง) */
export function downloadedWorkshopIds(ids: string[]): string[] {
  return ids.filter((id) => existsSync(workshopItemDir(id)));
}

/**
 * copy workshop content ที่โหลดมา → <install>/mods/workshop-<id> (refresh ทับของเดิม)
 * คืน { copied, missing } — missing = id ที่ยังไม่มีโฟลเดอร์ที่โหลดมา (โหลดไม่สำเร็จ)
 */
export async function copyDownloadedMods(
  dst: DSTConfig,
  ids: string[],
): Promise<{ copied: string[]; missing: string[] }> {
  const copied: string[] = [];
  const missing: string[] = [];
  for (const id of ids) {
    const src = workshopItemDir(id);
    if (!existsSync(src)) {
      missing.push(id);
      continue;
    }
    const dest = installedModDir(dst, id);
    await rm(dest, { recursive: true, force: true });
    await cp(src, dest, { recursive: true });
    copied.push(id);
  }
  return { copied, missing };
}

// ── legacy mods: ไฟล์มาเป็นก้อน *_legacy.bin (จริง ๆ คือ zip) ไม่ถูกแตก ──

/** ม็อดมี modinfo.lua (= ใช้งานได้/resolve ชื่อได้) ไหม */
function modExtracted(dst: DSTConfig, id: string): boolean {
  return existsSync(join(installedModDir(dst, id), "modinfo.lua"));
}

/** หา *_legacy.bin ในโฟลเดอร์ (คือ zip ที่ยังไม่แตก) */
function findLegacyBin(dir: string): string | null {
  if (!existsSync(dir)) return null;
  const f = readdirSync(dir).find((n) => /_legacy\.bin$/i.test(n));
  return f ? join(dir, f) : null;
}

/** copy ไฟล์ zip (.bin ก็ได้) ลงเป็น .zip ชั่วคราวใน destDir แล้วแตก (extractArchive ดูจากนามสกุล) */
async function unzipInto(zip: string, destDir: string): Promise<void> {
  mkdirSync(destDir, { recursive: true });
  const tmp = join(destDir, "__legacy_tmp.zip");
  copyFileSync(zip, tmp);
  try {
    await extractArchive(tmp, destDir);
  } finally {
    try {
      rmSync(tmp, { force: true });
    } catch {
      // ignore
    }
  }
}

export interface ModFixResult {
  fixed: string[];
  stillMissing: string[];
}

/**
 * ซ่อมม็อดที่ "ไม่มี modinfo.lua" (legacy/ไฟล์ไม่ครบ → server โชว์ workshop-id + ใช้ไม่ได้) แบบ hybrid:
 *  1) ถ้ามี *_legacy.bin (ใน mods/workshop-<id> หรือ workshop content) → unzip (มันคือ zip)
 *  2) ไม่งั้น → ดึง file_url จาก Steam (เฉพาะ legacy item มี) → โหลด zip → unzip
 * ลบ *_legacy.bin ทิ้งหลังแตกสำเร็จ
 */
export async function ensureModFilesExtracted(
  dst: DSTConfig,
  ids: string[],
  onLine: (line: string) => void,
): Promise<ModFixResult> {
  const missing = ids.filter((id) => !modExtracted(dst, id));
  const fixed: string[] = [];
  const stillMissing: string[] = [];
  if (missing.length === 0) return { fixed, stillMissing };

  onLine(`fixing ${missing.length} mod(s) without extracted files (legacy)...`);
  const urls = await fetchWorkshopFileUrls(missing); // best-effort (legacy item เท่านั้นที่มี)

  for (const id of missing) {
    const dir = installedModDir(dst, id);
    try {
      // 1) unzip *_legacy.bin ที่มีอยู่ (เร็ว/ออฟไลน์)
      const bin = findLegacyBin(dir) ?? findLegacyBin(workshopItemDir(id));
      if (bin) {
        onLine(`mod ${id}: unzip ${basename(bin)}`);
        await unzipInto(bin, dir);
      }
      // 2) ถ้ายังไม่มี modinfo → โหลดจาก file_url แล้วแตก
      if (!modExtracted(dst, id)) {
        const url = urls.get(id);
        if (url) {
          onLine(`mod ${id}: downloading from Steam file_url`);
          const res = await fetch(url);
          if (res.ok) {
            mkdirSync(dir, { recursive: true });
            const tmp = join(dir, "__dl.zip");
            writeFileSync(tmp, Buffer.from(await res.arrayBuffer()));
            try {
              await extractArchive(tmp, dir);
            } finally {
              try {
                rmSync(tmp, { force: true });
              } catch {
                // ignore
              }
            }
          }
        }
      }

      if (modExtracted(dst, id)) {
        fixed.push(id);
        const leftover = findLegacyBin(dir);
        if (leftover) {
          try {
            rmSync(leftover, { force: true });
          } catch {
            // ignore
          }
        }
      } else {
        stillMissing.push(id);
      }
    } catch (e) {
      onLine(`mod ${id}: fix failed — ${e instanceof Error ? e.message : String(e)}`);
      stillMissing.push(id);
    }
  }
  return { fixed, stillMissing };
}
